/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Person matte + face track for a camera video, on a background thread. Writes
 * `<outDir>/camera-matte.mp4` and `<outDir>/camera-faces.json` (atomically). Progress is 0..1.
 * Aborting the signal stops it and removes partial output; the promise then rejects.
 */
export declare function analyzeCamera(path: string, outDir: string, onProgress: (progress: number) => void, signal?: AbortSignal | undefined | null): Promise<CameraAnalysis>

/** Matches AudioSource in src/shared/project.ts. */
export interface AudioSourceInfo {
  file: string
  channels: number
  sampleRate: number
}

export interface CameraAnalysis {
  /** Absolute path of the grayscale person matte video (same timing as the camera). */
  matte: string
  /** Absolute path of the face track JSON: [{t, x, y, w, h}], normalized, top-left origin. */
  faces: string
  frames: number
  /** Face samples (about 10 per second) after gap filling; 0 when no face was ever seen. */
  faceSamples: number
}

export interface CameraDevice {
  id: string
  name: string
  kind: 'built-in' | 'external' | 'continuity' | 'ios'
  /**
   * Distinct sizes, tallest first (webcams: landscape only). Recording resolves the quality
   * the user picked (720, 1080, 2160) to the closest of these at 30 fps before it starts.
   */
  formats: Array<CameraFormat>
}

export interface CameraFormat {
  width: number
  height: number
  /** Highest frame rate of this size. */
  fps: number
}

export declare function cancelRecording(): Promise<RecState>

/**
 * PNG of `rect` (points relative to the display's top-left corner) at the display's pixel density,
 * without the cursor or Grip's own windows.
 */
export declare function captureScreenshot(displayId: number, rect: Rect): Promise<Buffer>

/** The display frozen for the picker: the screenshot without its PNG round trip. */
export declare function captureStill(displayId: number): Promise<Still>

/**
 * No zoom when the window shows: AppKit scales a window in over 150 ms, which would set the
 * picker's frozen screen moving. `handle`: BrowserWindow.getNativeWindowHandle(), its NSView.
 */
export declare function disableWindowAnimation(handle: Buffer): void

export interface Display {
  id: number
  name: string
  /** Global points, origin top-left of the main display. */
  frame: Rect
  pixelWidth: number
  pixelHeight: number
  scale: number
  refreshRate: number
  isMain: boolean
}

/** Webcams, Continuity Cameras, and iPhone/iPad screens connected over USB. */
export declare function listCameras(): Array<CameraDevice>

export declare function listDisplays(): Array<Display>

export declare function listMicrophones(): Array<Microphone>

export declare function listWindows(): Promise<Array<Window>>

/**
 * Whether the menu bar draws its icons white. It follows the wallpaper as well as the system
 * appearance, so it is read off the window of Grip's own menu bar icon, the app's appearance until
 * there is one.
 */
export declare function menuBarDark(): boolean

export interface MicLevel {
  /** Linear 0..1 over the last ~33 ms. */
  peak: number
  rms: number
}

export interface Microphone {
  id: string
  name: string
  isDefault: boolean
  isBuiltIn: boolean
}

/** Open the System Settings pane where the user turns `kind` on. */
export declare function openPermissionSettings(kind: Permission): void

export declare function pauseRecording(): RecState

export type Permission = 'screen' | 'accessibility' | 'microphone' | 'camera'

/** Current status. Screen Recording and Accessibility cannot tell "never asked" from "denied". */
export declare function permissionStatus(kind: Permission): PermissionStatus

export type PermissionStatus = 'granted' | 'denied' | 'notDetermined' | 'restricted'

/**
 * A point of a pen stroke drawn over the screen while recording, in global points: a stroke is
 * "start" (with its #rrggbb color and width in points), "move"s, and "end". It goes into the input
 * event stream on the session clock. False when nothing records it (no recording, or paused).
 */
export declare function recordDraw(phase: string, x: number, y: number, color?: string | undefined | null, width?: number | undefined | null): boolean

export type RecordingEvent =
  | { type: 'state'; state: RecState }
  | { type: 'warning'; code: string; message: string }
  | { type: 'finished'; bundleDir: string; reason: string; message?: string; sources: RecordingSources }
  | { type: 'cancelled'; bundleDir: string }

/** Matches Sources in src/shared/project.ts. */
export interface RecordingSources {
  duration: number
  screen?: VideoSourceInfo
  camera?: VideoSourceInfo
  mic?: AudioSourceInfo
  system?: AudioSourceInfo
  events?: string
}

export declare function recordingState(): RecState

export type RecState = 'idle' | 'starting' | 'recording' | 'paused' | 'stopping'

export interface Rect {
  x: number
  y: number
  w: number
  h: number
}

/**
 * A recording a crash or power loss cut short ends in movie fragments that the editor's demuxer
 * stops before: rewrite each such file as a regular MP4 (passthrough, no re-encode). Files that
 * are already whole are left alone. Rejects with the first file that could not be repaired.
 */
export declare function repairRecording(bundleDir: string): Promise<void>

/**
 * Ask for `kind` (the system prompt appears only the first time) and return the new status.
 * If it stays denied, send the user to `openPermissionSettings`.
 */
export declare function requestPermission(kind: Permission): Promise<PermissionStatus>

export declare function restartRecording(): Promise<RecState>

export declare function resumeRecording(): RecState

/**
 * From source time `t` on, stored frames must be turned `deg` degrees clockwise to be upright.
 * An iPhone/iPad changes its screen size when rotated; the file keeps the first frame's size and
 * orientation, so a frame of swapped size is stored turned 90° counter-clockwise (deg = 90).
 */
export interface Rotation {
  t: number
  deg: number
}

/** System Settings' window, or nothing when System Settings is not running. */
export declare function settingsWindow(): SettingsWindow | null

export interface SettingsWindow {
  /** Its frontmost window (global points), when one is on screen. */
  frame?: Rect
  /** Another app is in front: neither System Settings nor Grip is active. */
  covered: boolean
}

/** Meter `micId` (default mic when absent) at ~30 Hz until `stopMicMonitor`. Replaces a running meter. */
export declare function startMicMonitor(micId: string | undefined | null, onLevel: ((arg: MicLevel) => void)): Promise<void>

export interface StartOptions {
  /** The `.grip` bundle; files go to `<bundleDir>/sources/`. */
  bundleDir: string
  target: Target
  cameraId?: string
  micId?: string
  systemAudio: boolean
  /** Frames per second; default the display refresh rate, capped at 60. */
  fps?: number
  /** Leave the desktop icons out of display and area recordings. */
  hideDesktopIcons?: boolean
}

/**
 * Start recording. Resolves with the state once capture runs, rejects with a one-line reason.
 * `onEvent` receives state changes, warnings, and the finished recording (also when it ends on its own).
 */
export declare function startRecording(options: StartOptions, onEvent: ((arg: RecordingEvent) => void)): Promise<RecState>

/** A whole display as the screenshot sees it, in raw pixels: `data` is RGBA, Display P3. */
export interface Still {
  width: number
  height: number
  data: Buffer
}

export declare function stopMicMonitor(): void

/** Stop and finalize. Resolves with the sources (null when nothing was recording). */
export declare function stopRecording(): Promise<RecordingSources | null>

/**
 * What to record. An area rect is in points relative to its display's top-left corner. A window
 * `frame` (global points) moves and resizes the window there first, which needs Accessibility.
 * A device is an iPhone or iPad over USB (listCameras kind 'ios'); its audio is the system track.
 */
export type Target =
  | { kind: 'display'; displayId: number }
  | { kind: 'window'; windowId: number; frame?: Rect }
  | { kind: 'area'; displayId: number; rect: Rect }
  | { kind: 'device'; deviceId: string }
  | { kind: 'synthetic'; width?: number; height?: number }

/**
 * Transcribe the first audio track of `path`. `onProgress` gets 0..1; aborting `signal` stops
 * within one chunk and rejects with "Transcription cancelled".
 */
export declare function transcribe(path: string, opts: TranscribeOptions, onProgress: (progress: number) => void, signal?: AbortSignal | undefined | null): Promise<Array<TranscriptWord>>

export interface TranscribeOptions {
  /** Folder with encoder-model.int8.onnx, decoder_joint-model.int8.onnx and vocab.txt. */
  modelDir: string
}

export interface TranscriptWord {
  start: number
  end: number
  text: string
}

export declare function version(): string

/** Matches VideoSource in src/shared/project.ts. */
export interface VideoSourceInfo {
  file: string
  width: number
  height: number
  fps: number
  scale: number
  /** iPhone/iPad rotation changes (see camera::Rotation). */
  rotations?: Array<Rotation>
}

/**
 * Call `onChange` whenever a camera or iPhone/iPad is plugged in or out (then re-list).
 * Delivered through the main run loop. A later call replaces the previous callback.
 */
export declare function watchCameras(onChange: (() => void)): void

export interface Window {
  id: number
  title: string
  app: string
  bundleId: string
  /** Global points, origin top-left of the main display. */
  frame: Rect
}
