/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Person matte + face track for a camera video, on a background thread. Writes
 * `<outDir>/camera-matte.mp4` and `<outDir>/camera-faces.json` (atomically). Progress is 0..1.
 * Aborting the signal stops it and removes partial output; the promise then rejects.
 */
export declare function analyzeCamera(path: string, outDir: string, onProgress: (progress: number) => void, signal?: AbortSignal | undefined | null): Promise<CameraAnalysis>

export interface CameraAnalysis {
  /** Absolute path of the grayscale person matte video (same timing as the camera). */
  matte: string
  /** Absolute path of the face track JSON: [{t, x, y, w, h}], normalized, top-left origin. */
  faces: string
  frames: number
  /** Face samples (about 10 per second) after gap filling; 0 when no face was ever seen. */
  faceSamples: number
}

export interface CameraDevice {
  id: string
  name: string
  kind: 'built-in' | 'external' | 'continuity' | 'ios'
  /**
   * Distinct sizes, tallest first (webcams: landscape only). Recording resolves the quality
   * the user picked (720, 1080, 2160) to the closest of these at 30 fps before it starts.
   */
  formats: Array<CameraFormat>
}

export interface CameraFormat {
  width: number
  height: number
  /** Highest frame rate of this size. */
  fps: number
}

/** Webcams, Continuity Cameras, and iPhone/iPad screens connected over USB. */
export declare function listCameras(): Array<CameraDevice>

export declare function version(): string

/**
 * Call `onChange` whenever a camera or iPhone/iPad is plugged in or out (then re-list).
 * Delivered through the main run loop. A later call replaces the previous callback.
 */
export declare function watchCameras(onChange: (() => void)): void
