//! Native engine: everything that must talk to macOS frameworks.
//! JS contract: `native/index.d.ts` (generated by napi from the #[napi] items below).
//! Each module is owned by one domain; see AGENTS.md "Layout".

mod clock;
mod permissions; // capture
mod capture; // capture: ScreenCaptureKit screen + system audio, recording session
mod mic; // audio: microphone capture + level meter
mod camera; // camera: AVFoundation capture + Vision effects
mod input; // input-events: event tap, cursor images, key mapping
mod transcript; // transcript: Parakeet speech to text

#[napi_derive::napi]
pub fn version() -> String {
    env!("CARGO_PKG_VERSION").to_string()
}
